### ISSUE TITLE
[Request] Add more custom attributes that simulate weapons back from the Unofficial FF2

### ISSUE THREAD

**Issue by TheGreatWeegee** [Batfoxkid/Freak-Fortress-2-Rewrite#44]
## Description
Add more custom attributes that will allow to replicate weapons from the Unofficial FF2 - like shields blocking either one hit or working as an armor against boss's melee, and Short Circuit's stun/slow attribute.

## Applications
Possibility to partially restore weapon stuff back from Unofficial. I'm not really happy to see stun on SC again, but being able to put it back would be very nice.

## Other Information
No need to put it inside the default weapon config - I've seen that you add only key things to keep things balanced, but having them on wiki and being served together with Rewrite would be very nice.

**Comment by Frixux** [comment]
For me, its good idea.

**Comment by Batfoxkid** [comment]
Note that the `backstab shield` attribute does work on Demo Shields when applied.
And the Short Circuit slow is just an attribute but the stun is otherwise.
I'll likely not implement these myself as it's much more fit as an external subplugin making using of [TFCustAttr](https://github.com/nosoop/SM-TFCustAttr) and most changes were done just from attributes which can be readded if chose to.
However I'll likely accept pull requests for some that were logic on Unofficial or anything that may benefit the majority of servers.
But just so you don't have to go digging around for stuff:
- Red Tape Recorder marked for death for 4 seconds (8 on minions)
- Battalion's Backup granted an extra 50% damage resistance
- Phlogistinator granted 67% damage resistance during Mmmph
- Sydney Sleeper dealt less damage when the boss's rage was below 90%
- Short Circuit hard stunned the boss
- Third Degree granted 10% uber that was split between healing Medics
- Sandman hard stunned the boss
- Ullapool Caber had more than one use
